In [2]:
import numpy as np
def function1():
    arr = np.array([10,20,30,40,50,60])
    print(arr)
    print(f"Size = {arr.size}")

In [5]:
function1()

[10 20 30 40 50 60]
Size = 6


In [11]:
def function2(a):
    a1=np.array([1,2,3,4,])
    a2=np.array([7,4,3,2,])
    if a1[a]>a2[a]:
        print("a1 is greater")
    elif a1[a]<a2[a]:
        print("a2 is greater")
    else:
        print("equal")

In [15]:
function2(3)

a1 is greater


In [17]:
arr1=np.zeros(10)
arr2=np.ones(10)
arr3=np.ones(10)*5
arr4=np.ones(10)*10
arr5=np.ones(10)*50
arr6=np.ones(10)*20

In [18]:
print(arr1,arr2,arr3,arr4,arr5,arr6)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.] [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.] [50. 50. 50. 50. 50. 50. 50. 50. 50. 50.] [20. 20. 20. 20. 20. 20. 20. 20. 20. 20.]


In [20]:
arr = np.arange(30,70)
print(arr)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


In [21]:
arr1 = np.arange(50,95)
print(arr1)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94]


In [22]:
arr1 = np.arange(20,80,2)
print(arr1)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70 72 74 76 78]


In [23]:
arr1 = np.arange(21,80,2)
print(arr1)

[21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67
 69 71 73 75 77 79]


In [26]:
n1 = np.random.randint(10,40,15)
print(n1)

[11 36 13 16 38 11 39 25 21 31 26 36 37 16 20]


In [27]:
n2 = np.random.randint(30,50,10)
print(n2)

[35 46 39 34 39 35 45 42 45 39]


In [28]:
n3 = np.random.randint(50,90,20)
print(n3)

[52 77 72 54 62 80 65 74 60 79 67 54 70 67 82 78 78 62 69 60]


In [31]:
a1=np.array([1,2,3,4,])
a2=np.array([7,4,3,2,])
print(a1+a2,a1-a2,a1*a2,a1/a2)

[8 6 6 6] [-6 -2  0  2] [7 8 9 8] [0.14285714 0.5        1.         2.        ]


In [34]:
n1 = np.array([11,22,33,44,55,66,77,88,12,33,10,20])
n1 = n1.reshape([3,4])
print(n1)
print(f"NDIM: {n1.ndim}")
print(f"Shape = {n1.shape}")

[[11 22 33 44]
 [55 66 77 88]
 [12 33 10 20]]
NDIM: 2
Shape = (3, 4)


In [35]:
n1 = np.array([1,0,1,0,1,0,1,0,1])

In [37]:
n1 = n1.reshape([3,3])
print(n1)
print(f"NDIM: {n1.ndim}")
print(f"Shape = {n1.shape}")

[[1 0 1]
 [0 1 0]
 [1 0 1]]
NDIM: 2
Shape = (3, 3)


In [3]:
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
arr = np.diag([1,2,3,4,5])
print(arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [5]:
arr = np.random.random((3,3,3))
print(arr)

[[[6.83575470e-01 1.58850729e-01 7.47744051e-01]
  [8.67652287e-04 2.04999524e-01 4.30708020e-01]
  [6.13036036e-01 7.95399914e-01 4.64082031e-01]]

 [[1.51209710e-01 8.81629497e-01 8.60603782e-01]
  [9.68476852e-02 7.30113952e-01 1.18047614e-01]
  [3.67094474e-01 8.85459079e-01 1.23239890e-01]]

 [[4.09221357e-01 5.98158805e-01 9.14390993e-01]
  [8.05234018e-01 4.08600950e-01 8.29132204e-01]
  [1.61565442e-01 4.73957666e-01 7.15559440e-01]]]


In [6]:
arr = np.random.random((2,3,4))
print(arr)

[[[0.09115073 0.08464977 0.13332541 0.62880134]
  [0.11511259 0.64421852 0.16321824 0.95638874]
  [0.98798783 0.76918676 0.99766865 0.04697822]]

 [[0.00569912 0.66372491 0.29460557 0.40535532]
  [0.59655661 0.73655309 0.50484467 0.17201792]
  [0.0771095  0.59720796 0.01123447 0.8505617 ]]]


In [7]:
arr = np.array([10,20,30,40,50,60,70,80,90])
print(arr)
print(type(arr))

[10 20 30 40 50 60 70 80 90]
<class 'numpy.ndarray'>


In [8]:
arr = np.arange(2,11).reshape(3,3)
print(arr)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [9]:
arr = np.arange(12,38)
print(arr)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [10]:
arr = np.array([10,20,30,40,50])
print(arr[::-1])

[50 40 30 20 10]


In [11]:
arr = np.array([11,22,33,44],dtype=np.float16)
print(arr)
print(f"the data type is {arr.dtype}")

[11. 22. 33. 44.]
the data type is float16


In [12]:
l1 = [1,2,3,4,5,6,7,8,9]
print(f"the list is {l1}")
arr = np.array(l1)
print(f"list converted to array is {arr}")

the list is [1, 2, 3, 4, 5, 6, 7, 8, 9]
list converted to array is [1 2 3 4 5 6 7 8 9]


In [13]:
arr1 = np.array([10,20,30,45,65,32])
arr2 = np.array([2,5,4,6,3,8])
print(arr1%arr2)

[0 0 2 3 2 0]


In [14]:
arr = np.arange(20,50)
print(arr)
arr1 = (arr%3)
print(arr1)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49]
[2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1]
